FROM docker.io/library/fedora:40

ENV DEVCONTAINER=true

ARG workdir=/workspace
ARG chezmoi_path=${workdir}/.local/share/chezmoi

COPY devcontainers/distrobox-packages /tmp/

# hadolint ignore=SC2046,DL3041
RUN dnf install -y \
  $(cat /tmp/distrobox-packages) \
  && dnf clean all

COPY . ${chezmoi_path}

WORKDIR ${workdir}

RUN sh -c "$(curl -fsLS get.chezmoi.io)" -- \
  -b /usr/local/bin \
  apply \
  --destination ${workdir} \
  --source ${chezmoi_path} && \
  dnf clean all
